

set(PROJECT_SOURCE_FILES
    ${CORE_SOURCE_FILES}
    ${LINK_SOURCE_FILES}
    ${HTTP_SOURCE_FILES}
    )

set(PROJECT_HEADER_FILES
    ${CORE_HEADER_FILES}
    ${LINK_HEADER_FILES}
    ${HTTP_HEADER_FILES}
    )
