name: check clang-format

on:
  pull_request:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt install -y clang-format-11 git
    - name: clang-format
      run: clang-format-11 -style=file -i $(find include -type f)
    
    - name: check-changes
      run: bash -c '[ -z "$(git status --porcelain=v1 2>/dev/null)" ]'
